"use strict";const {WelcomeGoodbyeService}=require("../modules/welcome-goodbye/services/WelcomeGoodbyeService");const {WelcomeTemplateRenderer,defaultPlaceholderProviders}=require("../modules/welcome-goodbye/services/WelcomeTemplateRenderer");const {WelcomeGoodbyeLogService}=require("../modules/welcome-goodbye/services/WelcomeGoodbyeLogService");const {WelcomeTemplateRegistry}=require("../modules/welcome-goodbye/rendering/WelcomeTemplateRegistry");const {WelcomeResourceCache}=require("../modules/welcome-goodbye/rendering/WelcomeResourceCache");
const {WelcomeImageRenderer}=require("../modules/welcome-goodbye/image/rendering/WelcomeImageRenderer");const {WelcomeImagePipeline}=require("../modules/welcome-goodbye/image/pipeline/WelcomeImagePipeline");
const {WelcomeDeliveryService}=require("../modules/welcome-goodbye/services/WelcomeDeliveryService");const {handleMemberAdded}=require("../modules/welcome-goodbye/events/handleMemberAdded");const {handleMemberRemoved}=require("../modules/welcome-goodbye/events/handleMemberRemoved");const {adaptGuildMember}=require("../adapters/discord/DiscordGuildMemberAdapter");const {DiscordWelcomeGoodbyeTransport}=require("../adapters/discord/DiscordWelcomeGoodbyeTransport");
function createWelcomeGoodbyeRuntime({guildConfigResolver,logger=null,entitlementService=null}){
  // Phase 2 (P6) — la carte Welcome est une fonctionnalité Premium. La
  // composition injecte le singleton EntitlementService du processus : le
  // MÊME que /settings, l'aperçu Welcome et le panneau Admin, afin qu'il
  // n'existe qu'une seule autorité Premium (aucun cache, aucun resolveur
  // secondaire). Le require est paresseux : il évite un cycle de composition
  // au chargement et laisse les tests injecter un double.
  // En cas d'indisponibilité, `entitlementService` reste null et
  // WelcomeDeliveryService applique son repli fail-closed (ENTITLEMENT_UNAVAILABLE).
  const entitlement=entitlementService||(()=>{try{return require("./getEntitlementService").getEntitlementService();}catch{return null;}})();
  const service=new WelcomeGoodbyeService({guildConfigResolver});const logService=new WelcomeGoodbyeLogService({logger});const templateRegistry=new WelcomeTemplateRegistry();templateRegistry.discover();const imageRenderer=new WelcomeImageRenderer({resourceCache:new WelcomeResourceCache()});const imagePipeline=new WelcomeImagePipeline({renderer:imageRenderer,logService});const delivery=new WelcomeDeliveryService({renderer:new WelcomeTemplateRenderer({providers:defaultPlaceholderProviders()}),logService,imagePipeline,templateRegistry,entitlementService:entitlement});const invoke=(handler,member)=>handler({member:adaptGuildMember(member),service,delivery,transport:new DiscordWelcomeGoodbyeTransport(member)}).catch(error=>logger?.error?.("Welcome & Goodbye delivery failed",{error:error.message,guildId:member.guild.id}));return Object.freeze({handleMemberAdded:(member)=>invoke(handleMemberAdded,member),handleMemberRemoved:(member)=>invoke(handleMemberRemoved,member)});}module.exports={createWelcomeGoodbyeRuntime};
