"use strict";

const ErrorCode = Object.freeze({
  INTERNAL_ERROR: "INTERNAL_ERROR",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  AUTHORIZATION_DENIED: "AUTHORIZATION_DENIED",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  CONFIGURATION_UNAVAILABLE: "CONFIGURATION_UNAVAILABLE",
  CONFIGURATION_INVALID: "CONFIGURATION_INVALID",
  INTERACTION_UNSUPPORTED: "INTERACTION_UNSUPPORTED",
  BACKEND_UNAVAILABLE: "BACKEND_UNAVAILABLE",
  PERSISTENCE_FAILED: "PERSISTENCE_FAILED",
  PERSISTENCE_CONFLICT: "PERSISTENCE_CONFLICT",
  PERSISTENCE_SCHEMA_MISMATCH: "PERSISTENCE_SCHEMA_MISMATCH",
  PERSISTENCE_PERMISSION_DENIED: "PERSISTENCE_PERMISSION_DENIED",
  PREMIUM_REQUIRED: "PREMIUM_REQUIRED",
  ENTITLEMENT_UNAVAILABLE: "ENTITLEMENT_UNAVAILABLE",
  INTERACTION_EXPIRED: "INTERACTION_EXPIRED",
  INTERACTION_ALREADY_ACKNOWLEDGED: "INTERACTION_ALREADY_ACKNOWLEDGED",
  DISCORD_PERMISSION_DENIED: "DISCORD_PERMISSION_DENIED",
  DISCORD_RESOURCE_NOT_FOUND: "DISCORD_RESOURCE_NOT_FOUND",
  DISCORD_UNAVAILABLE: "DISCORD_UNAVAILABLE",
});

module.exports = { ErrorCode };
