"use strict";

/** Stable, transport-agnostic error codes exposed by the CIVRAT core contract. */
const ErrorCode = Object.freeze({
  AUTHORIZATION_DENIED: "AUTHORIZATION_DENIED",
  CONFIGURATION_INVALID: "CONFIGURATION_INVALID",
  CONFIGURATION_UNAVAILABLE: "CONFIGURATION_UNAVAILABLE",
  GUILD_CONTEXT_REQUIRED: "GUILD_CONTEXT_REQUIRED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INTERACTION_UNSUPPORTED: "INTERACTION_UNSUPPORTED",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  VALIDATION_FAILED: "VALIDATION_FAILED",
});

module.exports = { ErrorCode };
