"use strict";
const test = require("node:test");
const assert = require("node:assert/strict");
const { TicketService } = require("../services/TicketService");
function fixture({ ticket = { guild_id: "g", user_id: "owner", status: "open" }, target = { id: "target" }, support = false, add = { changed: true, code: "TICKET_MEMBER_ADDED" }, remove = { changed: true, code: "TICKET_MEMBER_REMOVED" } } = {}) {
  const service = new TicketService({ repository: { findByChannel: async () => ticket }, configService: { read: async () => ({ ticket_support_role_id: "support" }) }, transport: { isMemberInRole: async (member) => support && member.id === "staff", getGuildMember: async () => target, addTicketMemberAccess: async () => add, removeTicketMemberAccess: async () => remove } });
  return { service };
}
const base = { guildId: "g", channelId: "c", member: { id: "owner" }, targetMemberId: "target" };
test("owner and support manage ticket members", async () => { assert.equal((await fixture().service.updateMemberAccess({ ...base, action: "add" })).code, "TICKET_MEMBER_ADDED"); assert.equal((await fixture({ support: true }).service.updateMemberAccess({ ...base, member: { id: "staff" }, action: "remove" })).code, "TICKET_MEMBER_REMOVED"); });
test("member access validates ticket, guild, authorization and target", async () => { assert.equal((await fixture({ ticket: null }).service.updateMemberAccess({ ...base, action: "add" })).code, "TICKET_NOT_FOUND"); assert.equal((await fixture({ ticket: { guild_id: "g", status: "deleted", user_id: "owner" } }).service.updateMemberAccess({ ...base, action: "add" })).code, "TICKET_ALREADY_DELETED"); assert.equal((await fixture({ ticket: { guild_id: "x", user_id: "owner", status: "open" } }).service.updateMemberAccess({ ...base, action: "add" })).code, "TICKET_GUILD_MISMATCH"); assert.equal((await fixture().service.updateMemberAccess({ ...base, member: { id: "no" }, action: "add" })).code, "TICKET_UNAUTHORIZED"); assert.equal((await fixture({ target: null }).service.updateMemberAccess({ ...base, action: "add" })).code, "TICKET_MEMBER_NOT_FOUND"); });
test("remove protects creator and reports specific access states", async () => { assert.equal((await fixture().service.updateMemberAccess({ ...base, targetMemberId: "owner", action: "remove" })).code, "TICKET_MEMBER_NOT_ADDED"); assert.equal((await fixture({ add: { changed: false, code: "TICKET_MEMBER_ALREADY_ADDED" } }).service.updateMemberAccess({ ...base, action: "add" })).code, "TICKET_MEMBER_ALREADY_ADDED"); assert.equal((await fixture({ remove: { changed: false, code: "TICKET_MEMBER_NOT_ADDED" } }).service.updateMemberAccess({ ...base, action: "remove" })).code, "TICKET_MEMBER_NOT_ADDED"); });
