"use strict";
const { previewWelcomeImage } = require("./image/pipeline/previewWelcomeImage");
const { PermissionName } = require("../../core/permissions");
const { WelcomeGoodbyeComponentId: Id, WelcomeGoodbyeConfigKey: Key } = require("./configuration/welcomeGoodbyeConstants");
const { settingsView } = require("./interactions/welcomeGoodbyeViews");
const { toggleWelcome } = require("./interactions/updateWelcomeSettings");
const { openGoodbyeEmbedColorModal, submitGoodbyeEmbedColor } = require("./interactions/goodbyeEmbedColorModal");
const { toggleGoodbyeEmbed, previewGoodbyeEmbed } = require("./interactions/configureGoodbyeEmbed");
const { toggleGoodbye, useWelcomeChannelForGoodbye } = require("./interactions/configureGoodbye");
const { selectWelcomeGoodbyeChannel } = require("./interactions/selectWelcomeGoodbyeChannel");
const { openWelcomeMessageModal, submitWelcomeMessage } = require("./interactions/welcomeMessageModal");
const { openGoodbyeMessageModal, submitGoodbyeMessage } = require("./interactions/goodbyeMessageModal");
const { previewGoodbye } = require("./interactions/previewGoodbye");
const { testGoodbye } = require("./interactions/testGoodbye");
const { WelcomeAdminAction } = require("./services/WelcomeAdminLogService");
function registerWelcomeGoodbye({registry,service,adminLogService=null,settingsHome=null,imagePipeline=null}) { const permissions={allOf:[PermissionName.MANAGE_GUILD]}; const update=async(c)=>c.envelope.transport.update({view:settingsView({t:c.t,config:await service.get(c.guildId)})}); const log=(action,c)=>adminLogService?.record({action,guildId:c.guildId,actorId:c.userId}); registry.registerButton({customId:Id.PREVIEW_WELCOME_IMAGE,permissions,execute:async c=>previewWelcomeImage(c,imagePipeline)}); registry.registerButton({customId:Id.SECTION,permissions,execute:update}); registry.registerButton({customId:Id.TOGGLE_GOODBYE,permissions,execute:async c=>{const config=await toggleGoodbye({...c,settings:service});log(config[Key.GOODBYE_ENABLED]?WelcomeAdminAction.GOODBYE_ENABLED:WelcomeAdminAction.GOODBYE_DISABLED,c);return config;}}); registry.registerButton({customId:Id.SAME_CHANNEL,permissions,execute:async c=>{const config=await useWelcomeChannelForGoodbye({...c,settings:service});log(WelcomeAdminAction.SAME_CHANNEL_APPLIED,c);return config;}}); registry.registerSelectMenu({customId:Id.GOODBYE_CHANNEL_SELECT,permissions,execute:async c=>{const config=await selectWelcomeGoodbyeChannel({...c,settings:service,envelope:{...c.envelope,customId:Id.GOODBYE_CHANNEL}});log(WelcomeAdminAction.GOODBYE_CHANNEL_CHANGED,c);return config;}}); registry.registerButton({customId:Id.GOODBYE_MESSAGE,permissions,execute:async c=>openGoodbyeMessageModal({...c,settings:service,config:await service.get(c.guildId)})}); registry.registerModal({customId:Id.GOODBYE_MESSAGE,permissions,execute:async c=>{const config=await submitGoodbyeMessage({...c,settings:service});log("goodbye_message_changed",c);return config;}}); registry.registerButton({customId:Id.TOGGLE_GOODBYE_EMBED,permissions,execute:async c=>{const config=await toggleGoodbyeEmbed({...c,settings:service});log(config[Key.GOODBYE_EMBED]?WelcomeAdminAction.GOODBYE_EMBED_ENABLED:WelcomeAdminAction.GOODBYE_EMBED_DISABLED,c);return config;}}); registry.registerButton({customId:Id.GOODBYE_EMBED_COLOR,permissions,execute:async c=>openGoodbyeEmbedColorModal({...c,settings:service,config:await service.get(c.guildId)})}); registry.registerModal({customId:Id.GOODBYE_EMBED_COLOR,permissions,execute:async c=>{const config=await submitGoodbyeEmbedColor({...c,settings:service});log(WelcomeAdminAction.GOODBYE_EMBED_COLOR_CHANGED,c);return config;}}); registry.registerButton({customId:Id.PREVIEW_GOODBYE_EMBED,permissions,execute:async c=>previewGoodbyeEmbed({...c,settings:service})}); registry.registerButton({customId:Id.PREVIEW_GOODBYE,permissions,execute:async c=>previewGoodbye({...c,settings:service})}); registry.registerButton({customId:Id.TEST_GOODBYE,permissions,execute:async c=>testGoodbye({...c,settings:service})}); registry.registerButton({customId:Id.BACK,permissions,execute:settingsHome}); return {id:Id.SECTION,permissions}; }
module.exports={registerWelcomeGoodbye};
// Image preview registration is intentionally kept with the existing Welcome module routes.
