"use strict";
const { previewWelcomeImage } = require("./image/pipeline/previewWelcomeImage");
const { PermissionName } = require("../../core/permissions");
const { WelcomeGoodbyeComponentId: Id, WelcomeGoodbyeConfigKey: Key } = require("./configuration/welcomeGoodbyeConstants");
const { settingsView, welcomeView, goodbyeView } = require("./interactions/welcomeGoodbyeViews");
const { toggleWelcome } = require("./interactions/updateWelcomeSettings");
const { openGoodbyeEmbedColorModal, submitGoodbyeEmbedColor } = require("./interactions/goodbyeEmbedColorModal");
const { toggleGoodbyeEmbed, previewGoodbyeEmbed } = require("./interactions/configureGoodbyeEmbed");
const { toggleGoodbye, useWelcomeChannelForGoodbye } = require("./interactions/configureGoodbye");
const { selectWelcomeGoodbyeChannel } = require("./interactions/selectWelcomeGoodbyeChannel");
const { openWelcomeMessageModal, submitWelcomeMessage } = require("./interactions/welcomeMessageModal");
const { openGoodbyeMessageModal, submitGoodbyeMessage } = require("./interactions/goodbyeMessageModal");
const { toggleWelcomeEmbed, previewWelcomeEmbed } = require("./interactions/configureWelcomeEmbed");
const { openWelcomeEmbedColorModal, submitWelcomeEmbedColor } = require("./interactions/welcomeEmbedColorModal");
const { toggleWelcomeDm } = require("./interactions/configureWelcomeDm");
const { openWelcomeDmMessageModal, submitWelcomeDmMessage } = require("./interactions/welcomeDmMessageModal");
const { testWelcome } = require("./interactions/testWelcome");
const { testWelcomeDm } = require("./interactions/testWelcomeDm");
const { selectWelcomeTemplate } = require("./interactions/selectWelcomeTemplate");
const { previewGoodbye } = require("./interactions/previewGoodbye");
const { testGoodbye } = require("./interactions/testGoodbye");
const { WelcomeTemplateRenderer, defaultPlaceholderProviders } = require("./services/WelcomeTemplateRenderer");
const { WelcomeAdminAction } = require("./services/WelcomeAdminLogService");
function registerWelcomeGoodbye({registry,service,adminLogService=null,settingsHome=null,imagePipeline=null,templateRegistry=null}) { const permissions={allOf:[PermissionName.MANAGE_GUILD]}; const update=async(c)=>c.envelope.transport.update({view:settingsView({t:c.t,config:await service.get(c.guildId)})}); const log=(action,c)=>adminLogService?.record({action,guildId:c.guildId,actorId:c.userId});
  registry.registerButton({customId:Id.PREVIEW_WELCOME_IMAGE,permissions,execute:async c=>{
    const config=await service.get(c.guildId);
    const template=(templateRegistry&&(templateRegistry.get(config[Key.WELCOME_TEMPLATE])||templateRegistry.get("template-1")))||null;
    const dm=c.envelope.discordMember;
    const member={guildId:c.guildId,userId:c.userId,user:"@"+(dm?.user?.username||"user"),mention:"@"+(dm?.user?.username||"user"),username:dm?.user?.username||"user",displayName:dm?.displayName||dm?.user?.username||"CIVRAT",avatarUrl:dm?.user?.displayAvatarURL?.({extension:"png",size:256})||null,server:dm?.guild?.name||"CIVRAT",memberCount:dm?.guild?.memberCount,joinDate:dm?.joinedAt?.toLocaleDateString?.()};
    const subtitleText=new WelcomeTemplateRenderer({providers:defaultPlaceholderProviders()}).render(config[Key.WELCOME_MESSAGE]||"",member);
    return previewWelcomeImage(c,imagePipeline,{member,subtitleText,template});
  }});
  registry.registerButton({customId:Id.SECTION,permissions,execute:update});
  registry.registerButton({customId:Id.OPEN_WELCOME,permissions,execute:async c=>c.envelope.transport.update({view:welcomeView({t:c.t,config:await service.get(c.guildId)})})});
  registry.registerButton({customId:Id.OPEN_GOODBYE,permissions,execute:async c=>c.envelope.transport.update({view:goodbyeView({t:c.t,config:await service.get(c.guildId)})})});
  registry.registerButton({customId:Id.TOGGLE_WELCOME,permissions,execute:async c=>{const config=await toggleWelcome({...c,settings:service});log(config[Key.WELCOME_ENABLED]?WelcomeAdminAction.ENABLED:WelcomeAdminAction.DISABLED,c);return config;}});
  registry.registerSelectMenu({customId:Id.WELCOME_CHANNEL,permissions,execute:async c=>{const config=await selectWelcomeGoodbyeChannel({...c,settings:service,envelope:{...c.envelope,customId:Id.WELCOME_CHANNEL}});log(WelcomeAdminAction.CHANNEL_CHANGED,c);return config;}});
  registry.registerButton({customId:Id.WELCOME_MESSAGE,permissions,execute:async c=>openWelcomeMessageModal({...c,settings:service,config:await service.get(c.guildId)})});
  registry.registerModal({customId:Id.WELCOME_MESSAGE,permissions,execute:async c=>{const config=await submitWelcomeMessage({...c,settings:service,envelope:{...c.envelope,fields:c.envelope.modalValues}});log("welcome_message_changed",c);return config;}});
  registry.registerButton({customId:Id.TOGGLE_WELCOME_EMBED,permissions,execute:async c=>{const config=await toggleWelcomeEmbed({...c,settings:service});log(config[Key.WELCOME_EMBED]?WelcomeAdminAction.EMBED_ENABLED:WelcomeAdminAction.EMBED_DISABLED,c);return config;}});
  registry.registerButton({customId:Id.WELCOME_EMBED_COLOR,permissions,execute:async c=>openWelcomeEmbedColorModal({...c,settings:service,config:await service.get(c.guildId)})});
  registry.registerModal({customId:Id.WELCOME_EMBED_COLOR,permissions,execute:async c=>{const config=await submitWelcomeEmbedColor({...c,settings:service,envelope:{...c.envelope,fields:c.envelope.modalValues}});log(WelcomeAdminAction.EMBED_COLOR_CHANGED,c);return config;}});
  registry.registerButton({customId:Id.PREVIEW_WELCOME_EMBED,permissions,execute:async c=>previewWelcomeEmbed({...c,settings:service})});
  registry.registerButton({customId:Id.TOGGLE_WELCOME_DM,permissions,execute:async c=>{const config=await toggleWelcomeDm({...c,settings:service});log(config[Key.WELCOME_DM]?WelcomeAdminAction.DM_ENABLED:WelcomeAdminAction.DM_DISABLED,c);return config;}});
  registry.registerButton({customId:Id.WELCOME_DM_MESSAGE,permissions,execute:async c=>openWelcomeDmMessageModal({...c,settings:service,config:await service.get(c.guildId)})});
  registry.registerModal({customId:Id.WELCOME_DM_MESSAGE,permissions,execute:async c=>{const config=await submitWelcomeDmMessage({...c,settings:service,envelope:{...c.envelope,fields:c.envelope.modalValues}});log(WelcomeAdminAction.DM_MESSAGE_CHANGED,c);return config;}});
  registry.registerButton({customId:Id.TEST_WELCOME_DM,permissions,execute:async c=>testWelcomeDm({...c,settings:service,adminLogService})});
  registry.registerButton({customId:Id.TEST_WELCOME,permissions,execute:async c=>testWelcome({...c,settings:service,adminLogService})});
  registry.registerSelectMenu({customId:Id.TEMPLATE_SELECT,permissions,execute:async c=>{const config=await selectWelcomeTemplate({...c,settings:service});log(WelcomeAdminAction.TEMPLATE_CHANGED,c);return config;}});
  registry.registerButton({customId:Id.TOGGLE_GOODBYE,permissions,execute:async c=>{const config=await toggleGoodbye({...c,settings:service});log(config[Key.GOODBYE_ENABLED]?WelcomeAdminAction.GOODBYE_ENABLED:WelcomeAdminAction.GOODBYE_DISABLED,c);return config;}}); registry.registerButton({customId:Id.SAME_CHANNEL,permissions,execute:async c=>{const config=await useWelcomeChannelForGoodbye({...c,settings:service});log(WelcomeAdminAction.SAME_CHANNEL_APPLIED,c);return config;}}); registry.registerSelectMenu({customId:Id.GOODBYE_CHANNEL_SELECT,permissions,execute:async c=>{const config=await selectWelcomeGoodbyeChannel({...c,settings:service,envelope:{...c.envelope,customId:Id.GOODBYE_CHANNEL}});log(WelcomeAdminAction.GOODBYE_CHANNEL_CHANGED,c);return config;}}); registry.registerButton({customId:Id.GOODBYE_MESSAGE,permissions,execute:async c=>openGoodbyeMessageModal({...c,settings:service,config:await service.get(c.guildId)})}); registry.registerModal({customId:Id.GOODBYE_MESSAGE,permissions,execute:async c=>{const config=await submitGoodbyeMessage({...c,settings:service,envelope:{...c.envelope,fields:c.envelope.modalValues}});log("goodbye_message_changed",c);return config;}}); registry.registerButton({customId:Id.TOGGLE_GOODBYE_EMBED,permissions,execute:async c=>{const config=await toggleGoodbyeEmbed({...c,settings:service});log(config[Key.GOODBYE_EMBED]?WelcomeAdminAction.GOODBYE_EMBED_ENABLED:WelcomeAdminAction.GOODBYE_EMBED_DISABLED,c);return config;}}); registry.registerButton({customId:Id.GOODBYE_EMBED_COLOR,permissions,execute:async c=>openGoodbyeEmbedColorModal({...c,settings:service,config:await service.get(c.guildId)})}); registry.registerModal({customId:Id.GOODBYE_EMBED_COLOR,permissions,execute:async c=>{const config=await submitGoodbyeEmbedColor({...c,settings:service,envelope:{...c.envelope,fields:c.envelope.modalValues}});log(WelcomeAdminAction.GOODBYE_EMBED_COLOR_CHANGED,c);return config;}}); registry.registerButton({customId:Id.PREVIEW_GOODBYE_EMBED,permissions,execute:async c=>previewGoodbyeEmbed({...c,settings:service})}); registry.registerButton({customId:Id.PREVIEW_GOODBYE,permissions,execute:async c=>previewGoodbye({...c,settings:service})}); registry.registerButton({customId:Id.TEST_GOODBYE,permissions,execute:async c=>testGoodbye({...c,settings:service})}); registry.registerButton({customId:Id.BACK,permissions,execute:settingsHome}); return {id:Id.SECTION,permissions}; }
module.exports={registerWelcomeGoodbye};
// Image preview registration is intentionally kept with the existing Welcome module routes.
